{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rustium.configSecretName" . }}
  labels:
    {{- include "rustium.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.config.secretKey }}: |
    {{- .Values.config.content | nindent 4 }}
{{- end }}
